### ISSUE TITLE
Datablocks sanitize html update 2.12.1 requires webpack 5

### ISSUE THREAD

**Issue by ana-oprea** [eea/volto-datablocks#112]
Upgrading sanitize-html from version 2.7.3 to 2.12.2 introduces a module parsing error related to ES module syntax in a dependency (`htmlparser2`). This issue occurs when using webpack 4 as the module bundler.
```
./node_modules/sanitize-html/node_modules/htmlparser2/lib/esm/index.js 48:9
Module parse failed: Unexpected token (48:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * They should probably be removed eventually.
|  */
> export * as ElementType from "domelementtype";
| import { getFeed } from "domutils";
| export { getFeed } from "domutils";
```
The issue has also been discussed here: https://github.com/apostrophecms/sanitize-html/issues/663, and would be fixed by using webpack 5.

**Comment by ichim-david** [comment]
7.2.0 is using this version and is Volto 17 only
